name: well_nest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1  # HTTP client for API calls
  health: ^12.1.0  # For health data
  json_annotation: ^4.8.1  # For JSON serialization
  flutter_secure_storage: ^9.0.0  # For secure storage of tokens
  jwt_decoder: ^2.0.1  # For JWT token handling
  provider: ^6.0.5  # For state management
  fl_chart: ^0.71.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  open_filex: ^4.4.0
  path: ^1.9.0
  url_launcher: ^6.3.1
  flutter_doc_scanner: ^0.0.16  # For scanning documents

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8  # For code generation
  json_serializable: ^6.7.1  # For JSON serialization code generation

flutter:
  uses-material-design: true
