"""Add user authentication fields and refresh tokens

Revision ID: 58911f23e967
Revises: 25719113c965
Create Date: 2025-04-17 12:13:38.952168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58911f23e967'
down_revision = '25719113c965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=500), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint('uq_users_phone_number', ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_phone_number', type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
